
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int LT = 15;
  public static final int ELSE = 20;
  public static final int PLUS = 9;
  public static final int INT = 23;
  public static final int RBRACE = 5;
  public static final int RPAREN = 7;
  public static final int WHILE = 21;
  public static final int SEMI = 2;
  public static final int RETURN = 22;
  public static final int IF = 19;
  public static final int GT = 17;
  public static final int LPAREN = 6;
  public static final int LBRACE = 4;
  public static final int ID = 26;
  public static final int LE = 16;
  public static final int INT_CONST = 27;
  public static final int COMMA = 3;
  public static final int FLOAT = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 12;
  public static final int GE = 18;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int FLOAT_CONST = 28;
  public static final int ASSIGN = 8;
  public static final int EQ = 13;
  public static final int VOID = 25;
  public static final int NEQ = 14;
  public static final int UMINUS = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EQ",
  "NEQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "INT",
  "FLOAT",
  "VOID",
  "ID",
  "INT_CONST",
  "FLOAT_CONST",
  "UMINUS"
  };
}

